version: '3.1'

services:
  server:
    image: server
    command: sh -c "sleep 2 && /server"
    ports:
      - 8901:8901
    environment:
      - "REDIS=redis:6379"
      - "PORT=8901"
      - "NATS=nats:4222"
    depends_on:
      - redis
      - nats
      - worker
  worker:
    image: worker
    command: sh -c "sleep 2 && /worker"
    environment:
      - "REDIS=redis:6379"
      - "NATS=nats:4222"
    depends_on:
      - redis
      - nats
  nats:
    image: nats:2.1.0
    ports:
      - 4222:4222
      - 8222:8222
  redis:
    image: redis:5.0-alpine
    ports:
      - 6378:6379
